#!/usr/bin/env python3
"""Generate Phase 2 SEO pages for EduMadras."""
import os

BASE = "/Users/mahesh/PROJECTS/edumadras/src/app"

PAGES = [
  {"slug":"government-arts-science-colleges-chennai","title":"Government Arts and Science Colleges in Chennai 2025","h1":"Government Arts & Science Colleges in Chennai 2025","desc":"Complete list of government arts and science colleges in Chennai with courses, fees & admission details.","kw":"government arts and science colleges in chennai","stream":"Arts & Science","city":"Chennai","state":"","type":"Government","limit":"","intro":"Chennai's government arts and science colleges offer world-class education at minimal fees. Institutions like Presidency College, Queen Mary's College, and Pachaiyappa's College provide affordable UG and PG programs in sciences, humanities, and commerce with strong academic traditions.","faq_q1":"Which are the best government arts and science colleges in Chennai?","faq_a1":"Presidency College, Queen Mary's College, Pachaiyappa's College, and Nandanam Government Arts College are among the top government institutions in Chennai.","faq_q2":"What are the fees for government arts colleges in Chennai?","faq_a2":"Government arts and science college fees range from ₹500–₹5,000 per year, making them the most affordable higher education option.","bc_label":"Govt. A&S Colleges","filter":"Government"},
  {"slug":"top-10-arts-science-colleges-chennai","title":"Top 10 Arts and Science Colleges in Chennai 2025","h1":"Top 10 Arts and Science Colleges in Chennai 2025","desc":"Top 10 arts and science colleges in Chennai ranked by NAAC, placements & academics.","kw":"top 10 arts and science colleges in chennai","stream":"Arts & Science","city":"Chennai","state":"","type":"","limit":"10","intro":"This curated list of the top 10 arts and science colleges in Chennai includes prestigious institutions like Loyola College, Stella Maris, and Presidency College ranked by NAAC accreditation, placement records, and academic excellence.","faq_q1":"What are the top 10 arts and science colleges in Chennai?","faq_a1":"Loyola College, Stella Maris College, Presidency College, MCC, Ethiraj College, WCC, and others form the top 10.","faq_q2":"Which Chennai arts college has the best placements?","faq_a2":"Loyola College and MCC have strong placement cells with companies recruiting for IT, banking, and consulting roles.","bc_label":"Top 10 A&S","filter":"Top 10"},
  {"slug":"top-5-arts-science-colleges-chennai","title":"Top 5 Arts and Science Colleges in Chennai 2025","h1":"Top 5 Arts and Science Colleges in Chennai 2025","desc":"The 5 best arts and science colleges in Chennai — NAAC rankings, courses & fees.","kw":"top 5 arts and science colleges in chennai","stream":"Arts & Science","city":"Chennai","state":"","type":"","limit":"5","intro":"Looking for only the very best? These 5 arts and science colleges in Chennai represent the absolute elite — each with NAAC A++ or A+ accreditation, decades of academic excellence, and strong alumni networks.","faq_q1":"Which are the top 5 arts colleges in Chennai?","faq_a1":"Loyola College, Stella Maris College, Presidency College, Madras Christian College, and Ethiraj College are widely considered the top 5.","faq_q2":"How to get admission in these top colleges?","faq_a2":"Apply directly through college websites based on +2 marks. Some conduct entrance exams. Apply early as seats fill fast.","bc_label":"Top 5 A&S","filter":"Top 5"},
  {"slug":"top-arts-science-colleges-chennai","title":"Top Arts and Science Colleges in Chennai 2025","h1":"Top Arts and Science Colleges in Chennai 2025","desc":"Best arts and science colleges in Chennai with rankings, courses, fees & placements.","kw":"top arts and science colleges in chennai","stream":"Arts & Science","city":"Chennai","state":"","type":"","limit":"","intro":"Chennai is home to some of India's finest arts and science colleges offering diverse programs in sciences, humanities, commerce, and computer applications. This comprehensive guide ranks every top institution with verified data.","faq_q1":"Which arts and science college is best in Chennai?","faq_a1":"Loyola College is consistently ranked #1 among arts and science colleges in Chennai based on NAAC, placements, and academic reputation.","faq_q2":"What is the admission process?","faq_a2":"Most colleges admit based on +2 marks via direct applications. Top colleges may have entrance tests or merit-based cutoffs.","bc_label":"Top A&S Colleges","filter":""},
  {"slug":"top-10-arts-science-colleges-tamilnadu","title":"Top 10 Arts and Science Colleges in Tamil Nadu 2025","h1":"Top 10 Arts and Science Colleges in Tamil Nadu 2025","desc":"Top 10 arts and science colleges in Tamil Nadu ranked by NAAC accreditation & academics.","kw":"top 10 arts and science colleges in tamilnadu","stream":"Arts & Science","city":"","state":"Tamil Nadu","type":"","limit":"10","intro":"This definitive ranking of the top 10 arts and science colleges across Tamil Nadu covers institutions from Chennai, Coimbatore, Madurai, and beyond — ranked by NAAC scores, faculty quality, and student outcomes.","faq_q1":"What are the top 10 arts colleges in Tamil Nadu?","faq_a1":"Loyola College, PSG CAS (Coimbatore), The American College (Madurai), Presidency College, Stella Maris, and others form the top 10.","faq_q2":"Which university affiliation is best for arts colleges in TN?","faq_a2":"Madras University, Bharathiar University (Coimbatore), and Bharathidasan University (Trichy) are the top affiliating universities.","bc_label":"Top 10 A&S TN","filter":"Top 10"},
  {"slug":"top-20-arts-science-colleges-tamilnadu","title":"Top 20 Arts and Science Colleges in Tamil Nadu 2025","h1":"Top 20 Arts and Science Colleges in Tamil Nadu 2025","desc":"Top 20 arts and science colleges in Tamil Nadu with NAAC rankings, courses & fees.","kw":"top 20 arts and science colleges in tamilnadu","stream":"Arts & Science","city":"","state":"Tamil Nadu","type":"","limit":"20","intro":"This expanded list of 20 arts and science colleges covers top institutions across all major cities in Tamil Nadu. From Loyola College in Chennai to PSG CAS in Coimbatore, find verified data on courses, fees, and campus facilities.","faq_q1":"How many arts and science colleges are in Tamil Nadu?","faq_a1":"Tamil Nadu has over 700 arts and science colleges across government, aided, and self-financing categories.","faq_q2":"Which district has the most arts colleges in TN?","faq_a2":"Chennai has the highest concentration, followed by Coimbatore, Madurai, and Tiruchirappalli.","bc_label":"Top 20 A&S TN","filter":"Top 20"},
  {"slug":"top-arts-science-colleges-tamilnadu","title":"Top Arts and Science Colleges in Tamil Nadu 2025","h1":"Top Arts and Science Colleges in Tamil Nadu 2025","desc":"Best arts and science colleges in Tamil Nadu with rankings, courses, fees & admissions.","kw":"top arts and science colleges in tamilnadu","stream":"Arts & Science","city":"","state":"Tamil Nadu","type":"","limit":"","intro":"Tamil Nadu's arts and science colleges span a rich spectrum from iconic government institutions to top private colleges. This comprehensive directory covers every notable institution across the state.","faq_q1":"Which is the best arts college in Tamil Nadu?","faq_a1":"Loyola College (Chennai) is consistently ranked #1. PSG CAS (Coimbatore) and The American College (Madurai) are also top-tier.","faq_q2":"What are the fees in TN arts colleges?","faq_a2":"Government: ₹500-5K/year. Aided: ₹5K-25K/year. Self-financing: ₹20K-1L/year.","bc_label":"Top A&S TN","filter":""},
  {"slug":"aeronautical-engineering-colleges-chennai","title":"Aeronautical Engineering Colleges in Chennai 2025","h1":"Aeronautical Engineering Colleges in Chennai 2025","desc":"Complete list of aeronautical engineering colleges in Chennai with fees, placements & admissions.","kw":"aeronautical engineering colleges in chennai","stream":"Engineering","city":"Chennai","state":"","type":"","limit":"","intro":"Chennai offers excellent options for aeronautical engineering education with colleges like MIT Anna University, Hindustan Institute of Technology, and Vel Tech offering specialized programs with strong industry connections to ISRO, HAL, and aerospace companies.","faq_q1":"Which Chennai colleges offer aeronautical engineering?","faq_a1":"MIT Anna University, Hindustan Institute of Technology, Vel Tech, and Jeppiaar Engineering College offer B.E Aeronautical Engineering.","faq_q2":"What is the scope of aeronautical engineering from Chennai?","faq_a2":"Excellent career prospects with ISRO, HAL, Boeing, Airbus, and defense organizations. Average packages range from ₹5-12 LPA.","bc_label":"Aeronautical Chennai","filter":"Aeronautical"},
  {"slug":"aerospace-engineering-colleges-chennai","title":"Aerospace Engineering Colleges in Chennai 2025","h1":"Aerospace Engineering Colleges in Chennai 2025","desc":"Aerospace engineering colleges in Chennai — fees, placements, eligibility & admission process.","kw":"aerospace engineering colleges in chennai","stream":"Engineering","city":"Chennai","state":"","type":"","limit":"","intro":"Aerospace engineering in Chennai combines aeronautical and astronautical engineering disciplines. Top institutions offer cutting-edge programs with research opportunities in satellite technology, propulsion systems, and aircraft design.","faq_q1":"What is the difference between aeronautical and aerospace engineering?","faq_a1":"Aerospace covers both atmospheric (aeronautical) and space (astronautical) engineering. Aeronautical focuses only on aircraft within Earth's atmosphere.","faq_q2":"Which Chennai college is best for aerospace?","faq_a2":"MIT Anna University and IIT Madras (at PG level) are the top choices for aerospace engineering in Chennai.","bc_label":"Aerospace Chennai","filter":"Aerospace"},
  {"slug":"biomedical-engineering-colleges-chennai","title":"Biomedical Engineering Colleges in Chennai 2025","h1":"Biomedical Engineering Colleges in Chennai 2025","desc":"Biomedical engineering colleges in Chennai with fees, placements & course details.","kw":"biomedical engineering colleges in chennai","stream":"Engineering","city":"Chennai","state":"","type":"","limit":"","intro":"Chennai is a major hub for biomedical engineering education with its proximity to world-class hospitals and medical device companies. Colleges like SSN, Rajalakshmi, and SRM offer specialized BME programs with excellent industry exposure.","faq_q1":"Which Chennai colleges offer biomedical engineering?","faq_a1":"SSN College, SRM Institute, Rajalakshmi Engineering College, and Sairam Engineering College offer B.E Biomedical Engineering.","faq_q2":"What is the career scope of biomedical engineering?","faq_a2":"Growing field with opportunities in medical devices, healthcare IT, hospitals, and pharma companies. Average packages: ₹4-8 LPA.","bc_label":"Biomedical Chennai","filter":"Biomedical"},
  {"slug":"engineering-colleges-chennai-low-fees","title":"Engineering Colleges in Chennai with Low Fees 2025","h1":"Engineering Colleges in Chennai with Low Fees 2025","desc":"Affordable engineering colleges in Chennai with low fees. Government & private colleges under ₹1 lakh/year.","kw":"engineering colleges in chennai with low fees","stream":"Engineering","city":"Chennai","state":"","type":"","limit":"","intro":"Affordable engineering education in Chennai is accessible through government colleges with fees as low as ₹25,000/year and select private colleges under ₹1 lakh/year. This guide lists all budget-friendly engineering colleges with verified fee structures and placement data.","faq_q1":"Which engineering colleges in Chennai have the lowest fees?","faq_a1":"Government colleges like CEG Anna University (₹25K/yr), MIT Anna University (₹25K/yr), and ACT (₹30K/yr) have the lowest fees.","faq_q2":"Can I get quality education at low-fee colleges?","faq_a2":"Absolutely. Government colleges like Anna University CEG have better placements than many expensive private colleges.","bc_label":"Low Fees","filter":"Low Fees"},
  {"slug":"marine-engineering-colleges-chennai","title":"Marine Engineering Colleges in Chennai 2025","h1":"Marine Engineering Colleges in Chennai 2025","desc":"Marine engineering colleges in Chennai with fees, placements, eligibility & admission process.","kw":"marine engineering colleges in chennai","stream":"Engineering","city":"Chennai","state":"","type":"","limit":"","intro":"Chennai, a major port city, is ideal for marine engineering education. The Indian Maritime University headquarters, AMET University, and other institutions offer comprehensive marine engineering programs with direct industry connections.","faq_q1":"Which Chennai colleges offer marine engineering?","faq_a1":"Indian Maritime University (IMU), AMET University, and Hindustan Institute are top choices for marine engineering in Chennai.","faq_q2":"What is the starting salary for marine engineers?","faq_a2":"Marine engineers start at ₹6-12 LPA and can earn ₹30-60 LPA with experience in international shipping companies.","bc_label":"Marine Chennai","filter":"Marine"},
  {"slug":"top-10-engineering-colleges-chennai-2025","title":"Top 10 Engineering Colleges in Chennai 2025 — Latest Rankings","h1":"Top 10 Engineering Colleges in Chennai 2025 — Updated Rankings","desc":"Latest 2025 rankings of top 10 engineering colleges in Chennai. Updated NIRF data, fees & placements.","kw":"top 10 engineering colleges in chennai 2024, top 10 engineering colleges chennai 2025","stream":"Engineering","city":"Chennai","state":"","type":"","limit":"10","intro":"This is the latest 2025 edition of the top 10 engineering colleges in Chennai, updated with the most recent NIRF rankings, placement data, and fee structures. Compare colleges using the most current verified information available.","faq_q1":"Has the 2025 ranking changed from 2024?","faq_a1":"Rankings may shift slightly year-to-year based on updated NIRF scores, but the top institutions (IIT Madras, CEG, SSN) consistently hold top positions.","faq_q2":"When are the 2025 NIRF rankings released?","faq_a2":"NIRF rankings are typically released in June-July by the Ministry of Education. This page will be updated accordingly.","bc_label":"2025 Rankings","filter":"2025"},
  {"slug":"aerospace-engineering-colleges-tamilnadu","title":"Aerospace Engineering Colleges in Tamil Nadu 2025","h1":"Aerospace Engineering Colleges in Tamil Nadu 2025","desc":"Complete list of aerospace engineering colleges in Tamil Nadu with fees, placements & admissions.","kw":"aerospace engineering colleges in tamilnadu","stream":"Engineering","city":"","state":"Tamil Nadu","type":"","limit":"","intro":"Tamil Nadu offers strong aerospace engineering programs across multiple cities. From IIT Madras research labs to dedicated aerospace departments at MIT Anna University and private colleges, the state provides excellent foundation for careers in aerospace and defense.","faq_q1":"Which TN colleges offer aerospace engineering?","faq_a1":"MIT Anna University, Kumaraguru College (Coimbatore), Hindusthan College, and others offer B.E/B.Tech in Aerospace Engineering.","faq_q2":"Is aerospace engineering a good career in India?","faq_a2":"Yes — with ISRO expansion, defense modernization, and private space companies, demand for aerospace engineers is growing rapidly.","bc_label":"Aerospace TN","filter":"Aerospace"},
  {"slug":"biomedical-engineering-colleges-tamilnadu","title":"Biomedical Engineering Colleges in Tamil Nadu 2025","h1":"Biomedical Engineering Colleges in Tamil Nadu 2025","desc":"Biomedical engineering colleges across Tamil Nadu with fees, placements & course details.","kw":"biomedical engineering colleges in tamilnadu","stream":"Engineering","city":"","state":"Tamil Nadu","type":"","limit":"","intro":"Tamil Nadu is a leader in biomedical engineering education with its strong healthcare ecosystem and medical device manufacturing clusters. Colleges across Chennai, Coimbatore, and other cities offer comprehensive BME programs.","faq_q1":"Which TN colleges offer biomedical engineering?","faq_a1":"SSN College, PSG Tech, SRM, Rajalakshmi, and several Anna University-affiliated colleges offer B.E Biomedical Engineering.","faq_q2":"What is the job scope for BME graduates in Tamil Nadu?","faq_a2":"Chennai's medical device corridor offers strong employment. GE Healthcare, Siemens, Philips, and local medtech companies actively recruit from TN colleges.","bc_label":"Biomedical TN","filter":"Biomedical"},
  {"slug":"chemical-engineering-colleges-tamilnadu","title":"Chemical Engineering Colleges in Tamil Nadu 2025","h1":"Chemical Engineering Colleges in Tamil Nadu 2025","desc":"Chemical engineering colleges in Tamil Nadu with fees, placements, eligibility & admissions.","kw":"chemical engineering colleges in tamilnadu","stream":"Engineering","city":"","state":"Tamil Nadu","type":"","limit":"","intro":"Tamil Nadu's petrochemical, pharmaceutical, and manufacturing industries create strong demand for chemical engineers. Top institutions like ACT (Anna University), NIT Trichy, and PSG Tech offer excellent chemical engineering programs.","faq_q1":"Which TN colleges offer chemical engineering?","faq_a1":"ACT Anna University, NIT Trichy, PSG Tech (Coimbatore), and Coimbatore Institute of Technology are top choices for chemical engineering.","faq_q2":"What are the career options after chemical engineering?","faq_a2":"Petrochemicals, pharmaceuticals, food processing, environmental engineering, and process industries. Average packages: ₹5-10 LPA.","bc_label":"Chemical TN","filter":"Chemical"},
  {"slug":"government-engineering-colleges-tamilnadu","title":"Government Engineering Colleges in Tamil Nadu 2025","h1":"Government Engineering Colleges in Tamil Nadu 2025","desc":"Complete list of government engineering colleges in Tamil Nadu. Low fees, TNEA cutoffs & placements.","kw":"government engineering colleges in tamilnadu","stream":"Engineering","city":"","state":"Tamil Nadu","type":"Government","limit":"","intro":"Tamil Nadu's government engineering colleges offer excellent education at highly subsidized fees. From Anna University campuses to district-level government colleges, these institutions provide quality technical education accessible to all students through TNEA counseling.","faq_q1":"How many government engineering colleges are in TN?","faq_a1":"Tamil Nadu has approximately 20+ government and government-aided engineering colleges including Anna University campuses and regional institutions.","faq_q2":"What are the fees in TN government engineering colleges?","faq_a2":"Government engineering college fees range from ₹25,000-50,000/year — significantly lower than private colleges.","bc_label":"Govt. Engg TN","filter":"Government"},
  {"slug":"engineering-colleges-tamilnadu-cutoff","title":"Engineering Colleges Tamil Nadu Cutoff 2025 — TNEA Marks","h1":"Engineering Colleges in Tamil Nadu — TNEA Cutoff 2025","desc":"Last year TNEA cutoff marks for all engineering colleges in Tamil Nadu. Branch-wise cutoffs for 2025 admissions.","kw":"last year cutoff engineering colleges tamilnadu, tnea cutoff 2025","stream":"Engineering","city":"","state":"Tamil Nadu","type":"","limit":"","intro":"Understanding TNEA cutoff marks is essential for choosing the right engineering college in Tamil Nadu. This comprehensive guide provides last year's cutoff data for all major colleges and branches, helping you predict your admission chances for the 2025 counseling session.","faq_q1":"What was the TNEA cutoff for top colleges in 2024?","faq_a1":"CEG Anna University CSE: ~197/200 cutoff. SSN CSE: ~195. MIT Anna University: ~194. Cutoffs vary by branch and category.","faq_q2":"How are TNEA cutoffs calculated?","faq_a2":"TNEA cutoff is based on +2 marks: (Maths + Physics + Chemistry) / 3 * 200/300. Total is normalized to 200.","bc_label":"TNEA Cutoff","filter":"Cutoff"},
  {"slug":"best-medical-colleges-chennai","title":"Best Medical Colleges in Chennai 2025 — Rankings & NEET Cutoff","h1":"Best Medical Colleges in Chennai 2025","desc":"Best medical colleges in Chennai ranked by NIRF. Compare NEET cutoffs, MBBS fees & placement records.","kw":"best medical colleges in chennai","stream":"Medical","city":"Chennai","state":"","type":"","limit":"","intro":"Chennai is home to India's most prestigious medical institutions. From the historic Madras Medical College to modern private universities, the city offers diverse MBBS programs with excellent clinical training opportunities across government and private hospitals.","faq_q1":"Which is the best medical college in Chennai?","faq_a1":"Madras Medical College (MMC) is the most prestigious government medical college. Sri Ramachandra and SRM Medical are top private choices.","faq_q2":"What NEET score is needed for medical colleges in Chennai?","faq_a2":"Government colleges require 550-650+ NEET marks. Private colleges accept from 400+ depending on quota and category.","bc_label":"Best Medical Chennai","filter":""},
  {"slug":"government-medical-colleges-chennai","title":"Government Medical Colleges in Chennai 2025","h1":"Government Medical Colleges in Chennai 2025 — NEET Cutoff & Fees","desc":"All government medical colleges in Chennai with MBBS fees, NEET cutoffs, seats & facilities.","kw":"government medical colleges in chennai","stream":"Medical","city":"Chennai","state":"","type":"Government","limit":"","intro":"Chennai's government medical colleges offer MBBS education at minimal fees with excellent clinical exposure across government hospitals. Institutions like MMC, Stanley, Kilpauk, and Omandurar provide world-class medical training at highly affordable costs.","faq_q1":"Which government medical colleges are in Chennai?","faq_a1":"Madras Medical College, Stanley Medical College, Kilpauk Medical College, and Omandurar Government Medical College are the main government institutions.","faq_q2":"What is the MBBS fee in government medical colleges?","faq_a2":"Government medical college fees are approximately ₹13,000-30,000 per year — significantly cheaper than private colleges.","bc_label":"Govt. Medical Chennai","filter":"Government"},
  {"slug":"private-medical-colleges-chennai-fees","title":"Private Medical Colleges in Chennai with Fees 2025","h1":"Private Medical Colleges in Chennai — Complete Fee Structure 2025","desc":"List of private medical colleges in Chennai with detailed MBBS fee structure, NEET cutoffs & admissions.","kw":"list of private medical colleges with fees, private medical colleges chennai fees","stream":"Medical","city":"Chennai","state":"","type":"Private","limit":"","intro":"Understanding the fee structure of private medical colleges in Chennai is crucial for financial planning. This guide provides verified, detailed MBBS fee breakdowns for every private medical institution in Chennai, including tuition, hostel, and other charges.","faq_q1":"What is the MBBS fee in private medical colleges in Chennai?","faq_a1":"Private MBBS fees range from ₹10-25 lakhs/year depending on the institution. Total course cost: ₹50 lakhs to ₹1.5 crores.","faq_q2":"Are there scholarships for private medical colleges?","faq_a2":"Yes, many private colleges offer merit scholarships for high NEET scorers. Some offer up to 50-100% fee waivers for top rankers.","bc_label":"Private Medical Fees","filter":"Private"},
  {"slug":"private-medical-colleges-chennai","title":"Private Medical Colleges in Chennai 2025","h1":"Private Medical Colleges in Chennai 2025","desc":"Complete list of private medical colleges in Chennai with fees, NEET cutoffs & placements.","kw":"private medical colleges in chennai","stream":"Medical","city":"Chennai","state":"","type":"Private","limit":"","intro":"Chennai's private medical colleges offer quality MBBS education with modern infrastructure and hospital affiliations. While fees are higher than government colleges, many private institutions provide excellent clinical exposure and placement support.","faq_q1":"Which are the best private medical colleges in Chennai?","faq_a1":"Sri Ramachandra, SRM Medical College, Saveetha Medical College, and Chettinad Medical College are top-rated private institutions.","faq_q2":"Is private medical college worth the fees?","faq_a2":"Top private colleges like Sri Ramachandra have excellent clinical training and global recognition. Consider ROI, clinical exposure, and hospital quality.","bc_label":"Private Medical","filter":"Private"},
  {"slug":"top-medical-colleges-chennai","title":"Top Medical Colleges in Chennai 2025","h1":"Top Medical Colleges in Chennai 2025","desc":"Top medical colleges in Chennai — government & private. NIRF rankings, NEET cutoffs & MBBS fees.","kw":"top medical colleges in chennai","stream":"Medical","city":"Chennai","state":"","type":"","limit":"","intro":"Chennai is one of India's premier medical education destinations with a mix of historic government colleges and modern private universities. This comprehensive ranking covers all top medical colleges with NIRF scores, NEET cutoffs, and verified fee structures.","faq_q1":"How many medical colleges are in Chennai?","faq_a1":"Chennai has approximately 15+ medical colleges including 4 government and several private institutions.","faq_q2":"Which Chennai medical college has the best hospital?","faq_a2":"Rajiv Gandhi Government General Hospital (MMC) and Sri Ramachandra Hospital are among the best teaching hospitals in Chennai.","bc_label":"Top Medical Chennai","filter":""},
]

TEMPLATE = '''import type {{ Metadata }} from "next";
import {{ fetchCollegesByFilter }} from "@/lib/seo/fetchColleges";
import {{ buildListingJsonLd }} from "@/lib/seo/jsonLd";
import {{ HeadJsonLd }} from "@/components/seo/HeadJsonLd";
import {{ SEOCollegeListing }} from "@/components/seo/SEOCollegeListing";

const PAGE_URL = "https://edumadras.com/{slug}";
const H1 = "{h1}";
const BREADCRUMBS = [{{ label: "{bc_label}", href: "/{slug}" }}];
const FAQ_ITEMS = [{{ question: "{faq_q1}", answer: "{faq_a1}" }}, {{ question: "{faq_q2}", answer: "{faq_a2}" }}];

export const metadata: Metadata = {{
  title: "{title} | EduMadras",
  description: "{desc}",
  keywords: "{kw}",
  alternates: {{ canonical: PAGE_URL }},
  openGraph: {{ title: "{title} | EduMadras", url: PAGE_URL, siteName: "EduMadras", type: "website", locale: "en_IN" }},
}};

export default async function Page() {{
  const colleges = await fetchCollegesByFilter({{ {filters} }});
  const jsonLdSchemas = buildListingJsonLd({{ h1: H1, pageUrl: PAGE_URL, colleges, breadcrumbs: BREADCRUMBS, faqItems: FAQ_ITEMS }});
  return (
    <>
      <HeadJsonLd schemas={{jsonLdSchemas}} />
      <SEOCollegeListing colleges={{colleges}} title="{title}" h1={{H1}} subtitle="{desc}" introText="{intro}" breadcrumbs={{BREADCRUMBS}} faqItems={{FAQ_ITEMS}} pageUrl={{PAGE_URL}} filterLabel="{filter}" />
    </>
  );
}}
'''

for p in PAGES:
    filters = []
    if p["stream"]: filters.append(f'stream: "{p["stream"]}"')
    if p["city"]: filters.append(f'city: "{p["city"]}"')
    if p["state"]: filters.append(f'state: "{p["state"]}"')
    if p["type"]: filters.append(f'type: "{p["type"]}"')
    if p["limit"]: filters.append(f'limit: {p["limit"]}')
    filter_str = ", ".join(filters)

    content = TEMPLATE.format(filters=filter_str, **p)
    dirpath = os.path.join(BASE, p["slug"])
    os.makedirs(dirpath, exist_ok=True)
    filepath = os.path.join(dirpath, "page.tsx")
    with open(filepath, "w") as f:
        f.write(content)
    print(f"Created: {p['slug']}")

print(f"\nDone! Created {len(PAGES)} Phase 2 pages.")
